### ISSUE TITLE
Transaction event?

### ISSUE THREAD

**Issue by kmturley** [Nikhil22/angular-truffle-starter-dapp#11]
When calling the sendCoin method you are returning a Promise:
https://github.com/Nikhil22/angular4-truffle-starter-dapp/blob/master/src/app/app.component.ts#L118

But as far as I can see that will only confirm the transaction was sent, returning a transaction ID. But not when it was actually completed.

Looks like you need to listen for an event. It seems as thought there is an event in the contract called Transfer:
https://github.com/Nikhil22/angular4-truffle-starter-dapp/blob/master/contracts/MetaCoin.sol#L23

Which you could listen to using a variation of:
```
this.MetaCoin.deployed().Transfer().watch(function(error, result) {
  if (!error) {
    console.log(result);
  } else {
    console.log(error);
  }
});
```

**Comment by Nikhil22** [comment]
Hm good point. If you make a PR I can review + merge.

**Comment by kmturley** [comment]
Yeah will do, trying to figure out the best way to approach callback hell. Using Promisesmight be the best approach, but don't think .watch() supports them so might need a custom Promise:

sendCoin = () => {
  const amount = this.sendingAmount;
  const receiver = this.recipientAddress;
  let meta;

  this.setStatus('Initiating transaction... (please wait)');

  this.MetaCoin
    .deployed()
    .then(instance => {
      meta = instance;
      return meta.sendCoin(receiver, amount, {
        from: this.account
      }).then((result) => {
        return new Promise((resolve, reject) => {
          meta.Transfer({ transactionHash: result.tx }).watch((e, r) => {
            if (!e) { resolve(r); } else { reject(e); }
          });
        });
      });
    })
    .then(() => {
      this.setStatus('Transaction complete!');
      this.refreshBalance();
    })
    .catch(e => {
      console.log(e);
      this.setStatus('Error sending coin; see log.');
    });
};

**Comment by Nikhil22** [comment]
The Q library has a `denodeify` method. It takes a function and converts it into a promise.

Example here: https://stackoverflow.com/questions/22519784/how-do-i-convert-an-existing-callback-api-to-promises
